plugins { id 'com.android.application' }

android {
    namespace 'com.moben.app'
    compileSdk 34
    ndkVersion "25.2.9519653"

    defaultConfig {
        applicationId "com.moben.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "0.18.8"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }

    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets', '../../projects', '../../assets']
        }
    }
}
